import type { Metadata } from "next";
import "./ui/global.css"
import Image from "next/image";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="fixed top-0 right-0 left-0 bg-black text-white pt-4 pb-4 pl-4 pr-4 flex justify-between align-middle">
          <Image src="/logo.svg" width={50} height={50} alt="Logo"/>
          <div className="flex align-middle w-50 justify-between">
            <Image src="/search.svg" width={25} height={25} alt="Search icon"/>
            <Image src="/new_post.svg" width={25} height={25} alt="Create new post icon"/>
            <Image src="/notifications.svg" width={25} height={25} alt="Notifications icon"/>
            <Image src="/default_profile.svg" width={25} height={25} alt="Profile picture"/>
          </div>
        </header>
        <main className="mt-22">{children}</main>
      </body>
    </html>
  );
}
